/*
 *
 * Dashboard constants
 *
 */

export const GET_CONVERSATIONS = 'app/Dashboard/GET_CONVERSATIONS';
export const GET_CONVERSATIONS_SUCCESS = 'app/Dashboard/GET_CONVERSATIONS_SUCCESS';
export const GET_CONVERSATIONS_FAIL = 'app/Dashboard/GET_CONVERSATIONS_FAIL';
export const OPEN_CONVERSATION = 'app/Dashboard/OPEN_CONVERSATION';
export const GET_CONVERSATION_DETAILS_SUCCESS = 'app/Dashboard/GET_CONVERSATION_DETAILS_SUCCESS';
export const SEND_NEW_MESSAGE = 'app/Dashboard/SEND_NEW_MESSAGE';
export const HANDLE_NEW_MESSAGE = 'app/Dashboard/HANDLE_NEW_MESSAGE';
export const CANCEL_SUBSCRIPTIONS_BY_ID = 'app/Dashboard/CANCEL_SUBSCRIPTIONS_BY_ID';
export const INIT_SUBSCRIPTION_WITH_ID = 'app/Dashboard/INIT_SUBSCRIPTION_WITH_ID';
export const SEARCH_FOR_USER = 'app/Dashboard/SEARCH_FOR_USER';
export const SEARCH_FOR_USER_RESULT = 'app/Dashboard/SEARCH_FOR_USER_RESULT';
export const START_NEW_CONVERSATION_WITH_USER = 'app/Dashboard/START_NEW_CONVERSATION_WITH_USER';
export const START_NEW_CONVERSATION_WITH_USER_RESULT =
  'app/Dashboard/START_NEW_CONVERSATION_WITH_USER_RESULT';

