/*
 *
 * Dashboard constants
 *
 */

export const GET_CONVERSATIONS = 'app/Dashboard/GET_CONVERSATIONS';
export const GET_CONVERSATIONS_SUCCESS = 'app/Dashboard/GET_CONVERSATIONS_SUCCESS';
export const GET_CONVERSATIONS_FAIL = 'app/Dashboard/GET_CONVERSATIONS_FAIL';
export const OPEN_CONVERSATION = 'app/Dashboard/OPEN_CONVERSATION';
export const GET_CONVERSATION_DETAILS_SUCCESS = 'app/Dashboard/GET_CONVERSATION_DETAILS_SUCCESS';
export const SEND_NEW_MESSAGE = 'app/Dashboard/SEND_NEW_MESSAGE';
export const HANDLE_NEW_MESSAGE = 'app/Dashboard/HANDLE_NEW_MESSAGE';
export const CANCEL_SUBSCRIPTIONS_BY_ID = 'app/Dashboard/CANCEL_SUBSCRIPTIONS_BY_ID';
export const INIT_SUBSCRIPTION_WITH_ID_AND_TYPE = 'app/Dashboard/INIT_SUBSCRIPTION_WITH_ID_AND_TYPE';
export const START_NEW_CONVERSATION_WITH_USER_RESULT =
  'app/Dashboard/START_NEW_CONVERSATION_WITH_USER_RESULT';
export const INIT_SESSION_NOTIFICATIONS_SUBSCRIPTION_SUCCESS =
  'app/Dashboard/INIT_SESSION_NOTIFICATIONS_SUBSCRIPTION_SUCCESS';
export const GENERAL_SESSION_NOTIFICATION_RECEIVED =
  'app/Dashboard/GENERAL_SESSION_NOTIFICATION_RECEIVED';
